version: '3.1'

services:
  mariadb:
    image: 'mariadb:11.0'
    container_name: online_learning_platform_mariadb
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_USER}'
      - 'MYSQL_DATABASE=${MARIADB_DB_NAME}'
      - 'MYSQL_USER=${MARIADB_DB_USER}'
      - 'MYSQL_PASSWORD=${MARIADB_DB_PASSWORD}'
    ports:
      - '3308:3308'

  database:
    image: 'mariadb:11.0'
    container_name: online_learning_platform_database
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_USER}'
      - 'MYSQL_DATABASE=${MARIADB_DB_NAME}'
      - 'MYSQL_USER=${MARIADB_DB_USER}'
      - 'MYSQL_PASSWORD=${MARIADB_DB_PASSWORD}'
    ports:
      - '3307:3307'

  webserver:
    image: 'nginx:alpine'
    container_name: online_learning_platform_webserver
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '1001:80'

  php-fpm:
    build: phpdocker/php-fpm
    container_name: online_learning_platform_php
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    working_dir: /application
    expose:
      - 9000
    environment:
      - XDEBUG_SESSION=1
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - '.:/application'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
      - './phpdocker/php-fpm/xdebug.ini:/etc/php/8.2/fpm/conf.d/docker-php-ext-xdebug.ini'
      - './phpdocker/php-fpm/error_reporting.ini:/etc/php/8.2/fpm/conf.d/error_reporting.ini'

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    container_name: online_learning_platform_phpmyadmin
    ports:
      - '1002:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=online_learning_platform_mariadb

  mailer:
    container_name: online_learning_platform_mailer
    image: schickling/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'
