name: "Online Learning Platform"

on:
  push:
  pull_request:
    branches:
      - "development"
      - "main"

jobs:
  static-analysis-phpstan:
    name: "Static Analysis by PHPStan"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout Repostories"
        uses: "actions/checkout@v3"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1

      - name: "Install composer dependencies"
        uses: "ramsey/composer-install@2.2.0"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "PHPStan"
        run: "vendor/bin/phpstan analyse --memory-limit=-1"

  coding-standards:
    name: "Check Coding Standards"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout Repositories"
        uses: "actions/checkout@v3"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1

      - name: "Install composer dependencies"
        uses: "ramsey/composer-install@2.2.0"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "Coding Standard"
        run: "vendor/bin/phpcs src/ --standard=psr12"